version: '3.1'

services:
  db:
    image: postgres
    container_name: dashboard-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/data/pgdata

  server:
    container_name: dashboard-server
    build: .
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - db


volumes:
  pg-data:
